### ISSUE TITLE
Restart Button isn't centered

### ISSUE THREAD

**Issue by Vidhijain20** [AsCress/Rubik-Cube#1]
Issue:
When the game starts by double-clicking, the restart button that appears is not aligned in the center of the screen.

Solution:
The format has been updated so that the restart button will now appear centered.

Steps Taken:

Identified the Issue: Restart button misalignment upon game start.
Implemented Changes: Modified the format to ensure central alignment of the restart button.
Verification: Confirmed that the restart button now appears in the center of the screen.
This ensures a better user experience by making the restart button easily accessible and aesthetically pleasing.

**Comment by AsCress** [comment]
Welcome @Vidhijain20 !!
